# Server Conf

server:
  port: 9000

# Spring conf
spring:
  # App conf
  application:
    name: api
  # Mysql conf
  datasource:
    url: jdbc:mysql://localhost:3306/noeldb
    username: root
    password: root
  # Jpa conf
  jpa:
    hibernate:
      ddl-auto: update