name: Pull request Workflow

on:
  pull_request:
    branches:
     - main
jobs:
  test-unitaire:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du repo
        uses: actions/checkout@v2
      - name: Récupération de java
        uses: actions/setup-java@v2
        with:
         distribution: adopt
         java-version: 11
      - name: Création du jar
        run: mvn package
      - name: Upload jar
        uses: actions/upload-artefact@v2
        with:
          name: app.jar
          path: ./target/testDemo-0.0.1-SNAPSHOT.jar


