name: Workflow push

on:
  push:

jobs:
  test-unitaire:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du repo
        uses: actions/checkout@v2
      - name: Récupération de java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: Execution des tests
        run: mvn test